#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory

cd nonNewtonianPhaseChangeMultiphaseEuler
./Allwclean
cd ../
wclean

#------------------------------------------------------------------------------
